// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Paula_Medeia_Proiect.Data;

#nullable disable

namespace Paula_Medeia_Proiect.Migrations
{
    [DbContext(typeof(Paula_Medeia_ProiectContext))]
    [Migration("20250108163555_Stylist")]
    partial class Stylist
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Paula_Medeia_Proiect.Models.SalonBranch", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("SalonBranch");
                });

            modelBuilder.Entity("Paula_Medeia_Proiect.Models.Service", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<int?>("SalonBranchID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StylistID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SalonBranchID");

                    b.HasIndex("StylistID");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("Paula_Medeia_Proiect.Models.Stylist", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Stylist");
                });

            modelBuilder.Entity("Paula_Medeia_Proiect.Models.Service", b =>
                {
                    b.HasOne("Paula_Medeia_Proiect.Models.SalonBranch", "SalonBranch")
                        .WithMany("Services")
                        .HasForeignKey("SalonBranchID");

                    b.HasOne("Paula_Medeia_Proiect.Models.Stylist", "Stylist")
                        .WithMany("Services")
                        .HasForeignKey("StylistID");

                    b.Navigation("SalonBranch");

                    b.Navigation("Stylist");
                });

            modelBuilder.Entity("Paula_Medeia_Proiect.Models.SalonBranch", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("Paula_Medeia_Proiect.Models.Stylist", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
